### ISSUE TITLE
Move to ETHSecurity

### ISSUE THREAD

**Issue by fubuloubu** [trailofbits/blockchain-security-contacts#70]
As a public resource, this list might be more maintainable if managed within the ethsecurity organization by multiple parties. We could definitely add key maintainers from @trailofbits!

**Comment by fubuloubu** [comment]
Got something started [here](https://github.com/ethsecurity/contact-info) to show what I mean

**Comment by dguido** [comment]
Your fork violates the terms of the license on this repo.

**Comment by decanus** [comment]
@dguido, should community initiatives really prevent forking?

**Comment by dguido** [comment]
https://github.com/trailofbits/blockchain-security-contacts/blob/master/LICENSE
