### ISSUE TITLE
Security Firms section?

### ISSUE THREAD

**Issue by fubuloubu** [trailofbits/blockchain-security-contacts#73]
I noticed Zeppelin wasn't there. Do we want a section for security firms?

**Comment by dguido** [comment]
Zeppelin should be there for maintaining a common library of code, but not for their work as a security consulting firm. My approach has been to only list firms that have a direct responsibility for deployed products and services.

**Comment by fubuloubu** [comment]
That line gets blurry with some of the other teams. I'll add it to the ETHSecurity one. Added ToB's there.

**Comment by dguido** [comment]
Consensys Diligence hosts a Mythril decentralized app, so they should be on the list as a decentralized application. But Trail of Bits does not host any infrastructure that others depend on, therefore, no mention is required.

**Comment by fubuloubu** [comment]
Okay!
